"""
Django settings for PP_Journal project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os

from django.contrib.auth import logout
from dotenv import load_dotenv
from pathlib import Path

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-in3-dqehd3ues-k@qms5t#jmf(4ld$by(_m!1nh!2)-+beafww'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "app_weight.apps.AppWeightConfig",
    "app_growth.apps.AppGrowthConfig",
    "app_pressure.apps.AppPressureConfig",
    "app_pulse.apps.AppPulseConfig",
    'app_users.apps.AppUsersConfig',
    'app_web.apps.AppWebConfig'
    # 'app_growth',
    # 'app_pressure',
    # 'app_pulse',
    # 'app_weight'
    # 'app_users',
    # 'app_web',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app_users.middleware.EndActivityMiddleware'
]

ROOT_URLCONF = 'PP_Journal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PP_Journal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# SQL lite in project
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

  # postgre sqlserver - create .evn file - from .evn_template
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'HOST': os.getenv('postgresql.host'),
#         'PORT': os.getenv('postgresql.port'),
#         'NAME': os.getenv('postgresql.name'),
#         'USER': os.getenv('postgresql.user'),
#         'PASSWORD': os.getenv('postgresql.pass'),
#     }
# }

#   microsoft sqlserver - create .evn file - from .evn_template - check install driver ODBC
# DATABASES = {
#     'default': {
#         'ENGINE': 'mssql',
#         'HOST': os.getenv('mssql.host'),
#         'PORT': os.getenv('mssql.port'),
#         'NAME': os.getenv('mssql.name'),
#         'USER': os.getenv('mssql.user'),
#         'PASSWORD': os.getenv('mssql.pass'),
#         'OPTIONS': {
#             'DRIVER': 'ODBC Driver 18 for SQL Server',
#             'extra_params': 'Encrypt=no',
#         }
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'pl'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# My new User Permissions for abstractbaseuser
# AUTH_USER_MODEL = 'app_users.CustomUser'

# My login session settings
# SESSION_COOKIE_AGE = 604800  # 1 tydzień
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Sesja wygasa po zamknięciu przeglądarki

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/users/login'
LOGIN_URL = '/users/login'