# Generated by Django 5.0.8 on 2024-08-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pulse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse', models.DecimalField(decimal_places=1, max_digits=5)),
                ('date', models.DateTimeField()),
                ('comments', models.CharField(max_length=255)),
            ],
        ),
    ]
